on:
 workflow_dispatch:

name: CreatePDFs

jobs:
  makepdfs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: shrink/actions-document-publish@v1
      id: publish-document
      with:
            sources: 'README.md'
    - uses: actions/upload-artifact@v2
      with:
          name: 'document.pdf'
          path: ${{ steps.publish-document.outputs.pdf }}

